### ISSUE TITLE
Port the normal calendar controller

### ISSUE THREAD

**Issue by bintzandt** [bintzandt/CodeIgniter-Hydrofiel-v2#2]
Parent issue #1 

## Tasks
- [x] Implement the id route
- [x] Implement the calendar overview route
- [x] Implement sign-up functionality
- [x] Implement cancel functionality
- [x] Implement sign-up functionality for NSZK's
- [x] Implement edit-details functionality for NSZK's
