### ISSUE TITLE
Port the Admin/Event controller

### ISSUE THREAD

**Issue by bintzandt** [bintzandt/CodeIgniter-Hydrofiel-v2#6]
## Tasks
- [x] Port the index page
- [x] Port the edit / add event page
- [x] Port the edit registrations page
- [ ] Port the registration details page
- [x] Add styling to `tr` on hover so that the `clickable-row` class is no longer necessary.
